# Generated by Django 5.2.6 on 2025-09-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='contribution_score',
            field=models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', help_text='Estimated contribution to strategic objectives', max_length=10),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='impact_level',
            field=models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='interest_level',
            field=models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='priority',
            field=models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Calculated from impact x interest x influence', max_length=10),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='risk_level',
            field=models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Potential risk if stakeholder is disengaged', max_length=20),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='satisfaction_level',
            field=models.CharField(choices=[('very_low', 'Very Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', help_text='Stakeholder satisfaction with the project or SaaS', max_length=20),
        ),
    ]
