# Generated by Django 5.2.6 on 2025-09-30 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_plan', models.DecimalField(decimal_places=2, max_digits=12)),
                ('budget_used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='management_project.initiative')),
                ('organization_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management_project.organizationalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InitiativeResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(help_text='e.g., Person-hours, Equipment', max_length=50)),
                ('resource_required', models.DecimalField(decimal_places=2, max_digits=12)),
                ('resource_used', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='management_project.initiative')),
                ('organization_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management_project.organizationalprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InitiativeTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('initiative', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='management_project.initiative')),
                ('organization_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management_project.organizationalprofile')),
            ],
        ),
    ]
