# Generated by Django 5.2.6 on 2025-10-01 13:32

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='department',
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='role',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('owner', 'Owner'), ('executive', 'Executive'), ('manager', 'Manager'), ('department', 'Department'), ('Section', 'Section'), ('team', 'Team'), ('team_lead', 'Team Lead'), ('employee', 'Employee'), ('developer', 'Developer'), ('designer', 'Designer'), ('qa', 'Quality Assurance'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('it', 'IT Support'), ('operations', 'Operations'), ('logistics', 'Logistics'), ('product_owner', 'Product Owner'), ('scrum_master', 'Scrum Master'), ('analyst', 'Business Analyst'), ('trainer', 'Trainer'), ('mentor', 'Mentor'), ('intern', 'Intern'), ('contractor', 'Contractor'), ('customer', 'Customer'), ('partner', 'Partner'), ('supplier', 'Supplier'), ('investor', 'Investor'), ('funder', 'Funder'), ('regulator', 'Regulator'), ('community', 'Community'), ('consultant', 'Consultant'), ('advisor', 'Advisor'), ('board_member', 'Board Member'), ('volunteer', 'Volunteer'), ('researcher', 'Researcher'), ('media', 'Media'), ('government_official', 'Government Official'), ('auditor', 'Auditor'), ('legal', 'Legal Counsel'), ('other', 'Other')], default='employee', help_text='Select one or more roles', max_length=500),
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
