# Generated by Django 5.2.6 on 2025-09-10 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_statement', models.CharField(max_length=500)),
                ('organization_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management_project.organizationalprofile')),
            ],
        ),
    ]
