# Generated by Django 5.2.6 on 2025-09-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_project', '0002_remove_stakeholder_depends_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', help_text='Calculated from impact x interest x influence', max_length=10),
        ),
    ]
