# Generated by Django 5.2.6 on 2025-09-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management_project', '0002_initiativebudget_initiativeresource_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmploymentIncomeTaxBracket',
        ),
        migrations.DeleteModel(
            name='FuelForWorkRate',
        ),
        migrations.DeleteModel(
            name='FuelHomeToOfficeRate',
        ),
        migrations.DeleteModel(
            name='HardshipAllowanceRate',
        ),
        migrations.DeleteModel(
            name='OvertimeRate',
        ),
        migrations.DeleteModel(
            name='PensionRate',
        ),
        migrations.DeleteModel(
            name='PerDiemRate',
        ),
        migrations.DeleteModel(
            name='TransportForWorkRate',
        ),
        migrations.DeleteModel(
            name='TransportHomeToOfficeRate',
        ),
    ]
