# Generated by Django 5.2.6 on 2025-09-19 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_project', '0003_alter_stakeholder_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakeholder',
            name='contribution_score',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('very_high', 'Very High')], default='medium', help_text='Estimated contribution to strategic objectives', max_length=10),
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Calculated from impact x interest x influence', max_length=10),
        ),
    ]
