# Generated by Django 5.2.6 on 2025-09-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management_project', '0004_alter_stakeholder_contribution_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='strategicactionplan',
            name='slug',
        ),
        migrations.AlterField(
            model_name='stakeholder',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('executive', 'Executive'), ('employee', 'Employee'), ('manager', 'Manager'), ('team_lead', 'Team Lead'), ('developer', 'Developer'), ('designer', 'Designer'), ('qa', 'Quality Assurance'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('customer', 'Customer'), ('partner', 'Partner'), ('supplier', 'Supplier'), ('investor', 'Investor'), ('funder', 'Funder'), ('regulator', 'Regulator'), ('community', 'Community'), ('consultant', 'Consultant'), ('advisor', 'Advisor'), ('board_member', 'Board Member'), ('volunteer', 'Volunteer'), ('contractor', 'Contractor'), ('researcher', 'Researcher'), ('media', 'Media'), ('government_official', 'Government Official'), ('auditor', 'Auditor'), ('legal', 'Legal Counsel'), ('finance', 'Finance'), ('hr', 'Human Resources'), ('it', 'IT Support'), ('operations', 'Operations'), ('logistics', 'Logistics'), ('product_owner', 'Product Owner'), ('scrum_master', 'Scrum Master'), ('analyst', 'Business Analyst'), ('trainer', 'Trainer'), ('mentor', 'Mentor'), ('intern', 'Intern'), ('other', 'Other')], max_length=50),
        ),
    ]
