# Generated by Django 5.2 on 2025-08-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='copy_right',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='privacy',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='terms',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
