# Generated by Django 5.2 on 2025-08-08 10:18

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_sitesettings_copy_right_sitesettings_privacy_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='copy_right',
            field=tinymce.models.HTMLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='terms',
            field=tinymce.models.HTMLField(blank=True, max_length=500, null=True),
        ),
    ]
