# Generated by Django 5.2 on 2025-08-08 10:21

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0005_alter_sitesettings_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='copy_right',
            field=tinymce.models.HTMLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='privacy',
            field=tinymce.models.HTMLField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='terms',
            field=tinymce.models.HTMLField(blank=True, max_length=2000, null=True),
        ),
    ]
