# Generated by Django 5.2 on 2025-08-08 10:19

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_alter_sitesettings_copy_right_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='privacy',
            field=tinymce.models.HTMLField(blank=True, max_length=500, null=True),
        ),
    ]
