# Generated by Django 5.2 on 2025-08-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0006_alter_sitesettings_copy_right_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='copy_right',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
